import type { Metadata } from "next";
import {Forum, Geist, Geist_Mono} from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const forum = Forum({
    subsets: ["latin"],
    weight: "400", // فقط یک وزن داره
    variable: "--font-forum",
});

export const metadata: Metadata = {
  title: "Sense Of Stone",
  description: "Generated by Sorez",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${forum.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
