import type { Metadata } from "next";
import {Forum, Geist, Geist_Mono} from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const forum = Forum({
    subsets: ["latin"],
    weight: "400", // فقط یک وزن داره
    variable: "--font-forum",
});


//
// export const metadata: Metadata = {
//     title: "Sense Of Stone",
//     description: "Generated by Sorez",
//     openGraph: {
//         title: "Sense Of Stone",
//         description: "Generated by Sorez",
//         url: "https://senseofstone.co",
//         siteName: "Sense Of Stone",
//         images: [
//             {
//                 url: "https://senseofstone.co/images/og-image.png",
//                 width: 1200,
//                 height: 630,
//                 alt: "Sense Of Stone Preview",
//             },
//         ],
//         locale: "en_US",
//         type: "website",
//     },
//     twitter: {
//         card: "summary_large_image",
//         title: "Sense Of Stone",
//         description: "Generated by Sorez",
//         images: ["https://senseofstone.co/images/og-image.png"],
//     },
// };


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <head>
        <!-- Primary Meta Tags -->
        <title>Sense Of Stone</title>
        <meta name="title" content="Sense Of Stone" />
        <meta name="description" content="Generated by Sorez" />

        <!-- Open Graph / Facebook -->
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://www.senseofstone.co/" />
        <meta property="og:title" content="Sense Of Stone" />
        <meta property="og:description" content="Generated by Sorez" />
        <meta property="og:image" content="https://metatags.io/images/meta-tags.png" />

        <!-- Twitter -->
        <meta property="twitter:card" content="summary_large_image" />
        <meta property="twitter:url" content="https://www.senseofstone.co/" />
        <meta property="twitter:title" content="Sense Of Stone" />
        <meta property="twitter:description" content="Generated by Sorez" />
        <meta property="twitter:image" content="https://metatags.io/images/meta-tags.png" />

        <!-- Meta Tags Generated with https://metatags.io -->
    </head>
      <body
        className={`${forum.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
